name: Conformance Tests
description: run kubernetes gateway api conformance tests
runs:
  using: "composite"
  steps:
  - name: Prep Go Runner
    uses: ./.github/workflows/composite-actions/prep-go-runner
  - name: Install kind
    uses: helm/kind-action@v1.10.0
    with:
      install_only: true
      version: ${{ input.kube-version.kind }}
  - uses: azure/setup-kubectl@v4
    id: kubectl
    with:
      version: ${{ input.kube-version.kubectl }}
  - uses: azure/setup-helm@v4
    with:
      version: ${{ input.kube-version.helm }}
  - name: Set and retrieve environment variables
    shell: bash
    run: |
      # We want to conditionally set the VERSION variable based on the matrix value
      if [[ -z "${{ input.version }}" ]]; then
        echo "VERSION=$(make print-VERSION)" >> $GITHUB_ENV
      else
        # else, set the VERSION variable to the matrix value and
        # skip the docker build step so we use real image tags from
        # the helm repository.
        echo "VERSION=${{ input.version }}" >> $GITHUB_ENV
        echo "SKIP_DOCKER=true" >> $GITHUB_ENV
      fi
  - name: Setup test env
    shell: bash
    env:
      CLUSTER_NODE_VERSION: ${{ input.kube-version.node }}
      IMAGE_VARIANT: ${{ input.image-variant }}
      CONFORMANCE: "true"
    run: ./ci/kind/setup-kind.sh
  - name: Install Gloo Gateway with the k8s gateway integration enabled
    shell: bash
    run: |
      if [[ -z "${{ input.version }}" ]]; then
        # If input.version is empty, use the local chart path specified in the Makefile.
        helm upgrade -i -n gloo-system gloo ./_test/gloo-${VERSION}.tgz --create-namespace \
          --set kubeGateway.enabled=true \
          --set global.image.variant=${{ input.image-variant }}
      else
        # Else, use the provided version to install Gloo from the helm repository.
        helm upgrade -i -n gloo-system gloo gloo/gloo --version ${VERSION} --create-namespace \
          --set kubeGateway.enabled=true \
          --set global.image.variant=${{ input.image-variant }}
      fi
  - name: Run the kubernetes gateway API conformance tests
    shell: bash
    run: |
      # Default to the standard profile if none is provided. Otherwise,
      # assume the profile is experimental.
      if [[ -z ${{ input.profile }} || ${{ input.profile }} == "standard" ]]; then
        make conformance
      else
        make conformance-experimental
      fi
  - name: Capture debug information when tests fail
    if: ${{ failure() }}
    shell: bash
    run: kubectl -n gloo-system get events --sort-by='{.lastTimestamp}'
  - name: Upload conformace reports if profile is experimental
    if: "${{ input.profile == 'experimental' }}"
    uses: actions/upload-artifact@v4
    with:
      name: conformance-gloo-gateway-report
      path: _test/conformance/${{ env.VERSION }}-report.yaml
